/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prg381m2.prg381m2.View;

import javax.swing.JOptionPane;

/**
 *
 * @author Heiner
 */
public class FeedbackForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FeedbackForm.class.getName());

    /**
     * Creates new form FeedbackForm
     */
    public FeedbackForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FeedbackPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        FeedbackTitleTxt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        RatingTxt = new javax.swing.JLabel();
        Star1 = new javax.swing.JRadioButton();
        Star3 = new javax.swing.JRadioButton();
        Star2 = new javax.swing.JRadioButton();
        Star4 = new javax.swing.JRadioButton();
        Star5 = new javax.swing.JRadioButton();
        RatingClearBtn = new javax.swing.JButton();
        CommentTxt = new javax.swing.JLabel();
        CommentTxtArea = new javax.swing.JScrollPane();
        CommentsTxtArea = new javax.swing.JTextArea();
        SubmitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FeedbackPanel.setBackground(new java.awt.Color(255, 153, 0));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("MENU");

        homeBtn.setBackground(new java.awt.Color(255, 0, 0));
        homeBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setText("HOME");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(homeBtn)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exitBtn.setBackground(new java.awt.Color(255, 51, 0));
        exitBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("x");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        FeedbackTitleTxt.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        FeedbackTitleTxt.setForeground(new java.awt.Color(255, 255, 255));
        FeedbackTitleTxt.setText("Feedback");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 0)));

        RatingTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RatingTxt.setForeground(new java.awt.Color(0, 0, 0));
        RatingTxt.setText("Rating");

        Star1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Star1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starUnselected.png"))); // NOI18N
        Star1.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starSelected.png"))); // NOI18N
        Star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starUnselected.png"))); // NOI18N
        Star1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starSelected.png"))); // NOI18N
        Star1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Star1ActionPerformed(evt);
            }
        });

        Star3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Star3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starUnselected.png"))); // NOI18N
        Star3.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starSelected.png"))); // NOI18N
        Star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starUnselected.png"))); // NOI18N
        Star3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starSelected.png"))); // NOI18N
        Star3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Star3ActionPerformed(evt);
            }
        });

        Star2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Star2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starUnselected.png"))); // NOI18N
        Star2.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starSelected.png"))); // NOI18N
        Star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starUnselected.png"))); // NOI18N
        Star2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starSelected.png"))); // NOI18N
        Star2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Star2ActionPerformed(evt);
            }
        });

        Star4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Star4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starUnselected.png"))); // NOI18N
        Star4.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starSelected.png"))); // NOI18N
        Star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starUnselected.png"))); // NOI18N
        Star4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starSelected.png"))); // NOI18N
        Star4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Star4ActionPerformed(evt);
            }
        });

        Star5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Star5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starUnselected.png"))); // NOI18N
        Star5.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starSelected.png"))); // NOI18N
        Star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starUnselected.png"))); // NOI18N
        Star5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/prg381m2/prg381m2/View/starSelected.png"))); // NOI18N
        Star5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Star5ActionPerformed(evt);
            }
        });

        RatingClearBtn.setBackground(new java.awt.Color(255, 51, 51));
        RatingClearBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RatingClearBtn.setForeground(new java.awt.Color(255, 255, 255));
        RatingClearBtn.setText("Clear");
        RatingClearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RatingClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RatingClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Star1)
                .addGap(57, 57, 57)
                .addComponent(Star2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Star3)
                        .addGap(54, 54, 54)
                        .addComponent(Star4)
                        .addGap(43, 43, 43)
                        .addComponent(Star5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(RatingTxt)
                        .addGap(111, 111, 111)))
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RatingClearBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(RatingTxt)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Star1)
                    .addComponent(Star5)
                    .addComponent(Star3)
                    .addComponent(Star4)
                    .addComponent(Star2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(RatingClearBtn)
                .addContainerGap())
        );

        CommentTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CommentTxt.setForeground(new java.awt.Color(255, 255, 255));
        CommentTxt.setText("Any Comments?");

        CommentTxtArea.setBackground(new java.awt.Color(204, 204, 204));

        CommentsTxtArea.setBackground(new java.awt.Color(204, 204, 204));
        CommentsTxtArea.setColumns(20);
        CommentsTxtArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CommentsTxtArea.setForeground(new java.awt.Color(0, 0, 0));
        CommentsTxtArea.setRows(5);
        CommentsTxtArea.setText("(if any)Enter your comments here...");
        CommentTxtArea.setViewportView(CommentsTxtArea);

        SubmitBtn.setBackground(new java.awt.Color(255, 51, 51));
        SubmitBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SubmitBtn.setForeground(new java.awt.Color(255, 255, 255));
        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FeedbackPanelLayout = new javax.swing.GroupLayout(FeedbackPanel);
        FeedbackPanel.setLayout(FeedbackPanelLayout);
        FeedbackPanelLayout.setHorizontalGroup(
            FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FeedbackPanelLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(FeedbackTitleTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addComponent(exitBtn)
                        .addContainerGap())
                    .addGroup(FeedbackPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubmitBtn)
                            .addGroup(FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CommentTxtArea)
                                .addComponent(CommentTxt)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        FeedbackPanelLayout.setVerticalGroup(
            FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FeedbackPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(FeedbackPanelLayout.createSequentialGroup()
                        .addComponent(exitBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(FeedbackPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(FeedbackTitleTxt)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommentTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommentTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubmitBtn)
                .addGap(0, 258, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FeedbackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FeedbackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);

    }//GEN-LAST:event_exitBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        new Dashboard().setVisible(true); // Open new form
        dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void Star1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Star1ActionPerformed
        Star1.setSelected(true);  // Light up star1
        Star2.setSelected(false); // Dim star2 and higher
        Star3.setSelected(false);
        Star4.setSelected(false);
        Star5.setSelected(false);
    }//GEN-LAST:event_Star1ActionPerformed

    private void Star2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Star2ActionPerformed
        Star1.setSelected(true);  // Light up star1 and star2
        Star2.setSelected(true);
        Star3.setSelected(false); // Dim star3 and higher
        Star4.setSelected(false);
        Star5.setSelected(false);
    }//GEN-LAST:event_Star2ActionPerformed

    private void Star3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Star3ActionPerformed
        Star1.setSelected(true);  // Light up star1, star2, and star3
        Star2.setSelected(true);
        Star3.setSelected(true);
        Star4.setSelected(false); // Dim star4 and higher
        Star5.setSelected(false);
    }//GEN-LAST:event_Star3ActionPerformed

    private void Star4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Star4ActionPerformed
        Star1.setSelected(true);  // Light up star1, star2, star3, and star4
        Star2.setSelected(true);
        Star3.setSelected(true);
        Star4.setSelected(true);
        Star5.setSelected(false); // Dim star5
    }//GEN-LAST:event_Star4ActionPerformed

    private void Star5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Star5ActionPerformed
        Star1.setSelected(true);  // Light up all stars
        Star2.setSelected(true);
        Star3.setSelected(true);
        Star4.setSelected(true);
        Star5.setSelected(true);
    }//GEN-LAST:event_Star5ActionPerformed

    private void RatingClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RatingClearBtnActionPerformed
        Star1.setSelected(false);
        Star2.setSelected(false);
        Star3.setSelected(false);
        Star4.setSelected(false);
        Star5.setSelected(false);
    }//GEN-LAST:event_RatingClearBtnActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        int rating = 0;
        if (Star5.isSelected()) rating = 5;
        else if (Star4.isSelected()) rating = 4;
        else if (Star3.isSelected()) rating = 3;
        else if (Star2.isSelected()) rating = 2;
        else if (Star1.isSelected()) rating = 1;
        String comments = CommentsTxtArea.getText().trim();
        JOptionPane.showMessageDialog(this, "Feedback submitted");
        
        Star1.setSelected(false);
        Star2.setSelected(false);
        Star3.setSelected(false);
        Star4.setSelected(false);
        Star5.setSelected(false);
        CommentsTxtArea.setText("");
    }//GEN-LAST:event_SubmitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FeedbackForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CommentTxt;
    private javax.swing.JScrollPane CommentTxtArea;
    private javax.swing.JTextArea CommentsTxtArea;
    private javax.swing.JPanel FeedbackPanel;
    private javax.swing.JLabel FeedbackTitleTxt;
    private javax.swing.JButton RatingClearBtn;
    private javax.swing.JLabel RatingTxt;
    private javax.swing.JRadioButton Star1;
    private javax.swing.JRadioButton Star2;
    private javax.swing.JRadioButton Star3;
    private javax.swing.JRadioButton Star4;
    private javax.swing.JRadioButton Star5;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
